---
name: LevelLimiter
version: 2.0.0
main: MCA7\LevelLimiter\Main
api: 4.0.0
author: MCA7

permissions:
    levellimiter.bypass:
        description: "Allows the user to bypass level retriction"
        default: op
...
