---
name: LevelLimiter
version: 2.1.2
main: MCA7\LevelLimiter\Main
api: [ 4.0.0, 5.0.0 ]
author: MCA7
website: https://www.github.com/MCPEAbdu77/LevelLimiter

permissions:
    levellimiter.bypass:
        description: "Allows the user to bypass level retriction"
        default: op
...
