---
name: LevelLimiter
version: 1.0.0
main: MCA7\LevelLimiter\Main
api: 3.19.0
author: MCA7

permissions:
    level.bypass:
        description: "Allows the user to bypass level retriction"
        default: op
...
