# _                             _  
#| |       ___  __   __   ___  | | 
#| |      / _ \ \ \ / /  / _ \ | | 
#| |___  |  __/  \ V /  |  __/ | | 
#|_____|  \___|   \_/    \___| |_| 
# _       _               _   _                  
#| |     (_)  _ __ ___   (_) | |_    ___   _ __  
#| |     | | | '_ ` _ \  | | | __|  / _ \ | '__| 
#| |___  | | | | | | | | | | | |_  |  __/ | |    
#|_____| |_| |_| |_| |_| |_|  \__|  \___| |_|

# Usage =>
#
#  warp:             (This is the command)
#   - "worldname1"   (This is the name of the world which this cmd works on)
#   - "worldname2"   ( "" aka 'whitelisted' worlds)

command1:
  - "world"
  - "world2"
command2:
  - "world3"
  - "world4"

